### ISSUE TITLE
Issue when running IPC-Missile Visualizer branch.

### ISSUE THREAD

**Issue by Moodiment** [NGGameSim/NGGameSim#81]
Issue when running IPC-Missile Visualizer branch. Posting this for logging purposes. Preceding log dump was from SimViewer
```
Unhandled Exception: System.ArgumentException: Destination array is not long enough to copy all the items in the collection. Check array index and length.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.BitConverter.ToSingle(Byte[] value, Int32 startIndex)
   at Lidgren.Network.NetBuffer.ReadSingle()
   at NGSim.SimulationManager.TranslateMissilePacket(NetIncomingMessage msg) in H:\OneDrive\Github\NGGameSim\SimViewer\SimulationManager.cs:line 75
   at NGSim.Network.Client.Update(GameTime gameTime) in H:\OneDrive\Github\NGGameSim\SimViewer\Network\Client.cs:line 50
   at NGSim.SimViewer.Update(GameTime gameTime) in H:\OneDrive\Github\NGGameSim\SimViewer\SimViewer.cs:line 78
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at NGSim.Program.Main(String[] args) in H:\OneDrive\Github\NGGameSim\SimViewer\Program.cs:line 15
```
Would like input on to where this array is being overloaded, and why. Issue occurred without changing code, while running 3-4 games one after another, without re-opening executables.

Edit: Error only occurs when missiles have been fired.

**Comment by Moodiment** [comment]
This is due to the ToRemove list overflowing. An issue we had when continually running games togeather without removing items in the list. This should be fixed now with the most recent commit 7eb67618898e596aafe6718cbf7f60feacefc5e4.
